### ISSUE TITLE
set-window-rect?

### ISSUE THREAD

**Issue by tdrhq** [copyleft/cl-selenium-webdriver#1]
As far as I can tell this is unimplemented, right? I'm not a webdriver internals expert, but my understanding is this is what's used to resize the browser window? Is there another function in here for that purpose that I'm missing?

**Comment by tdrhq** [comment]
I think I've got everything else I needed to port my Selenium tests, I think this is the only thing left for me to completely remove the Java FFI. So thanks so much for this library!

**Comment by mmontone** [comment]
> As far as I can tell this is unimplemented, right?

I think so, yes. These whole section need to be implemented: https://www.w3.org/TR/webdriver1/#resizing-and-positioning-windows

**Comment by tdrhq** [comment]
I've been able to use `http-post-check` directly to work around the limitation. I'll send a PR to add a resize/set-window-rect

**Comment by mmontone** [comment]
That's great. Thanks!

**Comment by tdrhq** [comment]
Resolved in PR #2
